# purpose: look at values from US energy administration
# https://www.eia.gov/electricity/data/state/

library(tidyverse)
library(readxl)
library(patchwork)

rm(list = ls())



# data --------------------------------------------------------------------

d <- read_excel("data/source-of-electricity-data.xlsx",
                skip = 2) %>% 
  janitor::clean_names() %>% 
  filter(!(state_code %in% c("PR", "DC")))


d_1 <- 
  d %>% 
  filter(producer_type == "Total Electric Power Industry") %>% 
  select(year, state_code, fuel_source, nameplate_capacity_megawatts) %>% 
  filter(fuel_source != "All Sources") %>% 
  group_by(year, state_code) %>% 
  mutate(total = sum(nameplate_capacity_megawatts),
         pct = nameplate_capacity_megawatts/total * 100)


# figs --------------------------------------------------------------------

d_1 %>% 
  filter(fuel_source == "Petroleum",
         year == 1990) %>% 
  arrange(-pct)

d_1 %>% 
  group_by(fuel_source) %>% 
  mutate(mn = mean(pct)) %>% 
  arrange(-mn) %>% 
  mutate(fuel_source = fct_inorder(fuel_source)) %>% 
  #filter(fuel_source %in% c("Coal", "Solar Thermal and Photovoltaic", "Wind")) %>% 
  ggplot(aes(year, pct, group = state_code)) + 
  geom_line(color = "gray50") + 
  facet_wrap(~fuel_source) + 
  labs(title = "Percent of Energy Generated by Source",
       subtitle = "1990-2021, each line represents one state")
